// GENERATED by ios/tools/svg2shape.py from ios/DesignAssets/feenling-bloop.svg — DO NOT EDIT.
// Edit the SVG, preview in a browser, then rerun the script.
import SwiftUI

/// Layers of the character, unit-normalized from the SVG viewBox.
/// Draw into a rect with `aspectRatio` to keep proportions.
enum BloopPaths {
    static let aspectRatio: CGFloat = 1.2222

    static func tailFin(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.6727, 0.5, rect))
        p.addCurve(to: pt(0.9273, 0.3222, rect), control1: pt(0.7727, 0.3444, rect), control2: pt(0.8818, 0.2889, rect))
        p.addCurve(to: pt(0.8545, 0.5, rect), control1: pt(0.9091, 0.4111, rect), control2: pt(0.8864, 0.4611, rect))
        p.addCurve(to: pt(0.9273, 0.6778, rect), control1: pt(0.8864, 0.5389, rect), control2: pt(0.9091, 0.5889, rect))
        p.addCurve(to: pt(0.6727, 0.5, rect), control1: pt(0.8818, 0.7111, rect), control2: pt(0.7727, 0.6556, rect))
        p.closeSubpath()
        return p
    }

    static func topFin(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.3455, 0.2333, rect))
        p.addCurve(to: pt(0.5727, 0.0889, rect), control1: pt(0.3909, 0.1, rect), control2: pt(0.5, 0.0556, rect))
        p.addCurve(to: pt(0.4364, 0.2556, rect), control1: pt(0.5545, 0.1778, rect), control2: pt(0.5, 0.2333, rect))
        p.closeSubpath()
        return p
    }

    static func body(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.15 * rect.width, y: rect.minY + 0.2111 * rect.height, width: 0.5636 * rect.width, height: 0.6889 * rect.height))
        return p
    }

    static func belly(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.2227 * rect.width, y: rect.minY + 0.6444 * rect.height, width: 0.4182 * rect.width, height: 0.2222 * rect.height))
        return p
    }

    static func sideFin(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.4455, 0.6444, rect))
        p.addCurve(to: pt(0.5818, 0.6889, rect), control1: pt(0.5091, 0.6111, rect), control2: pt(0.5636, 0.6333, rect))
        p.addCurve(to: pt(0.4364, 0.6778, rect), control1: pt(0.5364, 0.7333, rect), control2: pt(0.4727, 0.7222, rect))
        p.closeSubpath()
        return p
    }

    static func eye(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.2545 * rect.width, y: rect.minY + 0.3944 * rect.height, width: 0.1273 * rect.width, height: 0.1667 * rect.height))
        return p
    }

    static func pupil(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.3045 * rect.width, y: rect.minY + 0.4611 * rect.height, width: 0.0545 * rect.width, height: 0.0667 * rect.height))
        return p
    }

    static func sparkle(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.3341 * rect.width, y: rect.minY + 0.4583 * rect.height, width: 0.0227 * rect.width, height: 0.0278 * rect.height))
        return p
    }

    static func mouth(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.1909 * rect.width, y: rect.minY + 0.6 * rect.height, width: 0.0727 * rect.width, height: 0.0667 * rect.height))
        return p
    }

    static func bubble1(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.7455 * rect.width, y: rect.minY + 0.1667 * rect.height, width: 0.0727 * rect.width, height: 0.0889 * rect.height))
        return p
    }

    static func bubble2(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.8295 * rect.width, y: rect.minY + 0.0917 * rect.height, width: 0.05 * rect.width, height: 0.0611 * rect.height))
        return p
    }

    static func bubble3(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.8727 * rect.width, y: rect.minY + 0.2111 * rect.height, width: 0.0364 * rect.width, height: 0.0444 * rect.height))
        return p
    }

    /// Paint-order layers with the authored fills.
    static let layers: [CharacterLayer] = [
        CharacterLayer(path: tailFin, color: Color(red: 0.1373, green: 0.502, blue: 0.6078)),
        CharacterLayer(path: topFin, color: Color(red: 0.1373, green: 0.502, blue: 0.6078)),
        CharacterLayer(path: body, color: Color(red: 0.1843, green: 0.6235, blue: 0.7451)),
        CharacterLayer(path: belly, color: Color(red: 0.749, green: 0.902, blue: 0.9373)),
        CharacterLayer(path: sideFin, color: Color(red: 0.1373, green: 0.502, blue: 0.6078)),
        CharacterLayer(path: eye, color: Color(red: 1, green: 1, blue: 1)),
        CharacterLayer(path: pupil, color: Color(red: 0.1725, green: 0.1373, blue: 0.2667)),
        CharacterLayer(path: sparkle, color: Color(red: 1, green: 1, blue: 1)),
        CharacterLayer(path: mouth, color: Color(red: 0.1137, green: 0.3922, blue: 0.4706)),
        CharacterLayer(path: bubble1, color: Color(red: 0.749, green: 0.902, blue: 0.9373), opacity: 0.9),
        CharacterLayer(path: bubble2, color: Color(red: 0.749, green: 0.902, blue: 0.9373), opacity: 0.9),
        CharacterLayer(path: bubble3, color: Color(red: 0.749, green: 0.902, blue: 0.9373), opacity: 0.9),
    ]

    private static func pt(_ x: CGFloat, _ y: CGFloat, _ rect: CGRect) -> CGPoint {
        CGPoint(x: rect.minX + x * rect.width, y: rect.minY + y * rect.height)
    }
}
