// GENERATED by ios/tools/svg2shape.py from ios/DesignAssets/feenling-chirp.svg — DO NOT EDIT.
// Edit the SVG, preview in a browser, then rerun the script.
import SwiftUI

/// Layers of the character, unit-normalized from the SVG viewBox.
/// Draw into a rect with `aspectRatio` to keep proportions.
enum ChirpPaths {
    static let aspectRatio: CGFloat = 1.0244

    static func tailTop(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.6952, 0.4195, rect))
        p.addCurve(to: pt(0.9429, 0.2634, rect), control1: pt(0.7905, 0.2927, rect), control2: pt(0.8857, 0.2439, rect))
        p.addCurve(to: pt(0.7238, 0.4683, rect), control1: pt(0.9238, 0.3415, rect), control2: pt(0.8476, 0.4195, rect))
        p.closeSubpath()
        return p
    }

    static func tailBottom(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.7143, 0.4683, rect))
        p.addCurve(to: pt(0.9619, 0.4098, rect), control1: pt(0.819, 0.4, rect), control2: pt(0.9143, 0.3805, rect))
        p.addCurve(to: pt(0.7238, 0.5171, rect), control1: pt(0.9238, 0.478, rect), control2: pt(0.819, 0.5171, rect))
        p.closeSubpath()
        return p
    }

    static func branch(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.2667, 0.9073, rect))
        p.addLine(to: pt(0.7524, 0.9073, rect))
        p.addCurve(to: pt(0.7857, 0.9317, rect), control1: pt(0.7714, 0.9073, rect), control2: pt(0.7857, 0.922, rect))
        p.addCurve(to: pt(0.7524, 0.9561, rect), control1: pt(0.7857, 0.9463, rect), control2: pt(0.7714, 0.9561, rect))
        p.addLine(to: pt(0.2667, 0.9561, rect))
        p.addCurve(to: pt(0.2333, 0.9317, rect), control1: pt(0.2476, 0.9561, rect), control2: pt(0.2333, 0.9463, rect))
        p.addCurve(to: pt(0.2667, 0.9073, rect), control1: pt(0.2333, 0.922, rect), control2: pt(0.2476, 0.9073, rect))
        p.closeSubpath()
        return p
    }

    static func legL(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.4, 0.8098, rect))
        p.addLine(to: pt(0.4286, 0.8098, rect))
        p.addLine(to: pt(0.4286, 0.922, rect))
        p.addLine(to: pt(0.4, 0.922, rect))
        p.closeSubpath()
        return p
    }

    static func legR(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.5238, 0.8098, rect))
        p.addLine(to: pt(0.5524, 0.8098, rect))
        p.addLine(to: pt(0.5524, 0.922, rect))
        p.addLine(to: pt(0.5238, 0.922, rect))
        p.closeSubpath()
        return p
    }

    static func body(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.4524, 0.2049, rect))
        p.addCurve(to: pt(0.7619, 0.5366, rect), control1: pt(0.6429, 0.2049, rect), control2: pt(0.7619, 0.3512, rect))
        p.addCurve(to: pt(0.4667, 0.8293, rect), control1: pt(0.7619, 0.7122, rect), control2: pt(0.6381, 0.8293, rect))
        p.addCurve(to: pt(0.181, 0.5268, rect), control1: pt(0.2952, 0.8293, rect), control2: pt(0.181, 0.7122, rect))
        p.addCurve(to: pt(0.4524, 0.2049, rect), control1: pt(0.181, 0.3415, rect), control2: pt(0.2762, 0.2049, rect))
        p.closeSubpath()
        return p
    }

    static func belly(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.2381 * rect.width, y: rect.minY + 0.5659 * rect.height, width: 0.381 * rect.width, height: 0.2341 * rect.height))
        return p
    }

    static func wing(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.5524, 0.439, rect))
        p.addCurve(to: pt(0.7238, 0.5756, rect), control1: pt(0.6667, 0.4195, rect), control2: pt(0.7333, 0.478, rect))
        p.addCurve(to: pt(0.5048, 0.6146, rect), control1: pt(0.6762, 0.6537, rect), control2: pt(0.5714, 0.6634, rect))
        p.addCurve(to: pt(0.5524, 0.439, rect), control1: pt(0.5048, 0.5366, rect), control2: pt(0.5143, 0.478, rect))
        p.closeSubpath()
        return p
    }

    static func eye(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.2762 * rect.width, y: rect.minY + 0.3561 * rect.height, width: 0.1143 * rect.width, height: 0.1268 * rect.height))
        return p
    }

    static func pupil(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.3214 * rect.width, y: rect.minY + 0.4073 * rect.height, width: 0.0524 * rect.width, height: 0.0537 * rect.height))
        return p
    }

    static func beakTop(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.2476, 0.4683, rect))
        p.addCurve(to: pt(0.0667, 0.4878, rect), control1: pt(0.1619, 0.4293, rect), control2: pt(0.0952, 0.4488, rect))
        p.addCurve(to: pt(0.2476, 0.5024, rect), control1: pt(0.1143, 0.5122, rect), control2: pt(0.1905, 0.5122, rect))
        p.closeSubpath()
        return p
    }

    static func beakBottom(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.2476, 0.5073, rect))
        p.addCurve(to: pt(0.119, 0.5902, rect), control1: pt(0.181, 0.5268, rect), control2: pt(0.1333, 0.5561, rect))
        p.addCurve(to: pt(0.2476, 0.5268, rect), control1: pt(0.1667, 0.5902, rect), control2: pt(0.219, 0.5561, rect))
        p.closeSubpath()
        return p
    }

    static func cheek(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.381 * rect.width, y: rect.minY + 0.4878 * rect.height, width: 0.0762 * rect.width, height: 0.078 * rect.height))
        return p
    }

    /// Paint-order layers with the authored fills.
    static let layers: [CharacterLayer] = [
        CharacterLayer(path: tailTop, color: Color(red: 0.8784, green: 0.4157, blue: 0.2667)),
        CharacterLayer(path: tailBottom, color: Color(red: 0.9608, green: 0.6392, blue: 0)),
        CharacterLayer(path: branch, color: Color(red: 0.5412, green: 0.4275, blue: 0.2471)),
        CharacterLayer(path: legL, color: Color(red: 0.7059, green: 0.3373, blue: 0.1843)),
        CharacterLayer(path: legR, color: Color(red: 0.7059, green: 0.3373, blue: 0.1843)),
        CharacterLayer(path: body, color: Color(red: 0.9608, green: 0.5412, blue: 0.3725)),
        CharacterLayer(path: belly, color: Color(red: 1, green: 0.9529, blue: 0.8784)),
        CharacterLayer(path: wing, color: Color(red: 0.8784, green: 0.4157, blue: 0.2667)),
        CharacterLayer(path: eye, color: Color(red: 1, green: 1, blue: 1)),
        CharacterLayer(path: pupil, color: Color(red: 0.1725, green: 0.1373, blue: 0.2667)),
        CharacterLayer(path: beakTop, color: Color(red: 0.9608, green: 0.6392, blue: 0)),
        CharacterLayer(path: beakBottom, color: Color(red: 0.8784, green: 0.5373, blue: 0)),
        CharacterLayer(path: cheek, color: Color(red: 0.8784, green: 0.4157, blue: 0.2667), opacity: 0.3),
    ]

    private static func pt(_ x: CGFloat, _ y: CGFloat, _ rect: CGRect) -> CGPoint {
        CGPoint(x: rect.minX + x * rect.width, y: rect.minY + y * rect.height)
    }
}
