// GENERATED by ios/tools/svg2shape.py from ios/DesignAssets/feenling-dot.svg — DO NOT EDIT.
// Edit the SVG, preview in a browser, then rerun the script.
import SwiftUI

/// Layers of the character, unit-normalized from the SVG viewBox.
/// Draw into a rect with `aspectRatio` to keep proportions.
enum DotPaths {
    static let aspectRatio: CGFloat = 1.1111

    static func antennaL(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.42, 0.1667, rect))
        p.addCurve(to: pt(0.3, 0.0667, rect), control1: pt(0.39, 0.1111, rect), control2: pt(0.35, 0.0778, rect))
        p.addCurve(to: pt(0.315, 0.1111, rect), control1: pt(0.295, 0.0889, rect), control2: pt(0.3, 0.1056, rect))
        p.addCurve(to: pt(0.405, 0.1833, rect), control1: pt(0.355, 0.1222, rect), control2: pt(0.385, 0.1444, rect))
        p.closeSubpath()
        return p
    }

    static func antennaR(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.58, 0.1667, rect))
        p.addCurve(to: pt(0.7, 0.0667, rect), control1: pt(0.61, 0.1111, rect), control2: pt(0.65, 0.0778, rect))
        p.addCurve(to: pt(0.685, 0.1111, rect), control1: pt(0.705, 0.0889, rect), control2: pt(0.7, 0.1056, rect))
        p.addCurve(to: pt(0.595, 0.1833, rect), control1: pt(0.645, 0.1222, rect), control2: pt(0.615, 0.1444, rect))
        p.closeSubpath()
        return p
    }

    static func antennaTipL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.265 * rect.width, y: rect.minY + 0.0444 * rect.height, width: 0.06 * rect.width, height: 0.0667 * rect.height))
        return p
    }

    static func antennaTipR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.675 * rect.width, y: rect.minY + 0.0444 * rect.height, width: 0.06 * rect.width, height: 0.0667 * rect.height))
        return p
    }

    static func head(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.35 * rect.width, y: rect.minY + 0.0944 * rect.height, width: 0.3 * rect.width, height: 0.3333 * rect.height))
        return p
    }

    static func eyeL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.4 * rect.width, y: rect.minY + 0.1667 * rect.height, width: 0.08 * rect.width, height: 0.1 * rect.height))
        return p
    }

    static func eyeR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.52 * rect.width, y: rect.minY + 0.1667 * rect.height, width: 0.08 * rect.width, height: 0.1 * rect.height))
        return p
    }

    static func pupilL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.43 * rect.width, y: rect.minY + 0.2056 * rect.height, width: 0.04 * rect.width, height: 0.0444 * rect.height))
        return p
    }

    static func pupilR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.53 * rect.width, y: rect.minY + 0.2056 * rect.height, width: 0.04 * rect.width, height: 0.0444 * rect.height))
        return p
    }

    static func body(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.11, 0.6111, rect))
        p.addCurve(to: pt(0.5, 0.2778, rect), control1: pt(0.11, 0.4, rect), control2: pt(0.28, 0.2778, rect))
        p.addCurve(to: pt(0.89, 0.6111, rect), control1: pt(0.72, 0.2778, rect), control2: pt(0.89, 0.4, rect))
        p.addCurve(to: pt(0.5, 0.9333, rect), control1: pt(0.89, 0.8056, rect), control2: pt(0.715, 0.9333, rect))
        p.addCurve(to: pt(0.11, 0.6111, rect), control1: pt(0.285, 0.9333, rect), control2: pt(0.11, 0.8056, rect))
        p.closeSubpath()
        return p
    }

    static func split(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.49, 0.2778, rect))
        p.addLine(to: pt(0.51, 0.2778, rect))
        p.addLine(to: pt(0.51, 0.9333, rect))
        p.addLine(to: pt(0.49, 0.9333, rect))
        p.closeSubpath()
        return p
    }

    static func dotBigL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.235 * rect.width, y: rect.minY + 0.4722 * rect.height, width: 0.15 * rect.width, height: 0.1667 * rect.height))
        return p
    }

    static func dotBigR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.615 * rect.width, y: rect.minY + 0.4722 * rect.height, width: 0.15 * rect.width, height: 0.1667 * rect.height))
        return p
    }

    static func dotSmallL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.36 * rect.width, y: rect.minY + 0.7222 * rect.height, width: 0.08 * rect.width, height: 0.0889 * rect.height))
        return p
    }

    static func dotSmallR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.56 * rect.width, y: rect.minY + 0.7222 * rect.height, width: 0.08 * rect.width, height: 0.0889 * rect.height))
        return p
    }

    /// Paint-order layers with the authored fills.
    static let layers: [CharacterLayer] = [
        CharacterLayer(path: antennaL, color: Color(red: 0.2902, green: 0.2314, blue: 0.4196)),
        CharacterLayer(path: antennaR, color: Color(red: 0.2902, green: 0.2314, blue: 0.4196)),
        CharacterLayer(path: antennaTipL, color: Color(red: 0.2902, green: 0.2314, blue: 0.4196)),
        CharacterLayer(path: antennaTipR, color: Color(red: 0.2902, green: 0.2314, blue: 0.4196)),
        CharacterLayer(path: head, color: Color(red: 0.2902, green: 0.2314, blue: 0.4196)),
        CharacterLayer(path: eyeL, color: Color(red: 1, green: 1, blue: 1)),
        CharacterLayer(path: eyeR, color: Color(red: 1, green: 1, blue: 1)),
        CharacterLayer(path: pupilL, color: Color(red: 0.1725, green: 0.1373, blue: 0.2667)),
        CharacterLayer(path: pupilR, color: Color(red: 0.1725, green: 0.1373, blue: 0.2667)),
        CharacterLayer(path: body, color: Color(red: 0.949, green: 0.4196, blue: 0.3098)),
        CharacterLayer(path: split, color: Color(red: 0.7882, green: 0.3098, blue: 0.2118)),
        CharacterLayer(path: dotBigL, color: Color(red: 0.2902, green: 0.2314, blue: 0.4196)),
        CharacterLayer(path: dotBigR, color: Color(red: 0.2902, green: 0.2314, blue: 0.4196)),
        CharacterLayer(path: dotSmallL, color: Color(red: 0.2902, green: 0.2314, blue: 0.4196)),
        CharacterLayer(path: dotSmallR, color: Color(red: 0.2902, green: 0.2314, blue: 0.4196)),
    ]

    private static func pt(_ x: CGFloat, _ y: CGFloat, _ rect: CGRect) -> CGPoint {
        CGPoint(x: rect.minX + x * rect.width, y: rect.minY + y * rect.height)
    }
}
