// GENERATED by ios/tools/svg2shape.py from ios/DesignAssets/feeny.svg — DO NOT EDIT.
// Edit the SVG, preview in a browser, then rerun the script.
import SwiftUI

/// Layers of the character, unit-normalized from the SVG viewBox.
/// Draw into a rect with `aspectRatio` to keep proportions.
enum FeenyPaths {
    static let aspectRatio: CGFloat = 0.9091

    static func stem(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.48, 0.2818, rect))
        p.addCurve(to: pt(0.505, 0.1591, rect), control1: pt(0.475, 0.2364, rect), control2: pt(0.48, 0.2, rect))
        p.addCurve(to: pt(0.53, 0.1682, rect), control1: pt(0.515, 0.1409, rect), control2: pt(0.54, 0.15, rect))
        p.addCurve(to: pt(0.51, 0.2773, rect), control1: pt(0.51, 0.2045, rect), control2: pt(0.505, 0.2364, rect))
        p.closeSubpath()
        return p
    }

    static func leafL(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.505, 0.1636, rect))
        p.addCurve(to: pt(0.39, 0.0636, rect), control1: pt(0.45, 0.1545, rect), control2: pt(0.4, 0.1182, rect))
        p.addCurve(to: pt(0.415, 0.0455, rect), control1: pt(0.39, 0.05, rect), control2: pt(0.4, 0.0409, rect))
        p.addCurve(to: pt(0.51, 0.1545, rect), control1: pt(0.47, 0.0591, rect), control2: pt(0.5, 0.1091, rect))
        p.closeSubpath()
        return p
    }

    static func leafR(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.515, 0.1545, rect))
        p.addCurve(to: pt(0.63, 0.0455, rect), control1: pt(0.53, 0.1, rect), control2: pt(0.57, 0.0545, rect))
        p.addCurve(to: pt(0.65, 0.0682, rect), control1: pt(0.645, 0.0455, rect), control2: pt(0.655, 0.0545, rect))
        p.addCurve(to: pt(0.525, 0.1636, rect), control1: pt(0.635, 0.1227, rect), control2: pt(0.58, 0.1545, rect))
        p.closeSubpath()
        return p
    }

    static func wingL(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.2, 0.5545, rect))
        p.addCurve(to: pt(0.06, 0.6909, rect), control1: pt(0.13, 0.5636, rect), control2: pt(0.07, 0.6182, rect))
        p.addCurve(to: pt(0.095, 0.7182, rect), control1: pt(0.06, 0.7091, rect), control2: pt(0.075, 0.7227, rect))
        p.addCurve(to: pt(0.23, 0.6, rect), control1: pt(0.165, 0.7, rect), control2: pt(0.21, 0.65, rect))
        p.closeSubpath()
        return p
    }

    static func wingR(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.8, 0.5545, rect))
        p.addCurve(to: pt(0.94, 0.6909, rect), control1: pt(0.87, 0.5636, rect), control2: pt(0.93, 0.6182, rect))
        p.addCurve(to: pt(0.905, 0.7182, rect), control1: pt(0.94, 0.7091, rect), control2: pt(0.925, 0.7227, rect))
        p.addCurve(to: pt(0.77, 0.6, rect), control1: pt(0.835, 0.7, rect), control2: pt(0.79, 0.65, rect))
        p.closeSubpath()
        return p
    }

    static func footL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.335 * rect.width, y: rect.minY + 0.9 * rect.height, width: 0.13 * rect.width, height: 0.0727 * rect.height))
        return p
    }

    static func footR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.535 * rect.width, y: rect.minY + 0.9 * rect.height, width: 0.13 * rect.width, height: 0.0727 * rect.height))
        return p
    }

    static func body(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.5, 0.2545, rect))
        p.addCurve(to: pt(0.83, 0.6273, rect), control1: pt(0.705, 0.2545, rect), control2: pt(0.83, 0.4318, rect))
        p.addCurve(to: pt(0.5, 0.9273, rect), control1: pt(0.83, 0.8136, rect), control2: pt(0.685, 0.9273, rect))
        p.addCurve(to: pt(0.17, 0.6273, rect), control1: pt(0.315, 0.9273, rect), control2: pt(0.17, 0.8136, rect))
        p.addCurve(to: pt(0.5, 0.2545, rect), control1: pt(0.17, 0.4318, rect), control2: pt(0.295, 0.2545, rect))
        p.closeSubpath()
        return p
    }

    static func belly(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.5, 0.5455, rect))
        p.addCurve(to: pt(0.7, 0.7318, rect), control1: pt(0.625, 0.5455, rect), control2: pt(0.7, 0.6318, rect))
        p.addCurve(to: pt(0.5, 0.9, rect), control1: pt(0.7, 0.8455, rect), control2: pt(0.61, 0.9, rect))
        p.addCurve(to: pt(0.3, 0.7318, rect), control1: pt(0.39, 0.9, rect), control2: pt(0.3, 0.8455, rect))
        p.addCurve(to: pt(0.5, 0.5455, rect), control1: pt(0.3, 0.6318, rect), control2: pt(0.375, 0.5455, rect))
        p.closeSubpath()
        return p
    }

    static func eyeL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.335 * rect.width, y: rect.minY + 0.4091 * rect.height, width: 0.14 * rect.width, height: 0.1455 * rect.height))
        return p
    }

    static func eyeR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.535 * rect.width, y: rect.minY + 0.4091 * rect.height, width: 0.14 * rect.width, height: 0.1455 * rect.height))
        return p
    }

    static func pupilL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.3875 * rect.width, y: rect.minY + 0.4614 * rect.height, width: 0.065 * rect.width, height: 0.0591 * rect.height))
        return p
    }

    static func pupilR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.5575 * rect.width, y: rect.minY + 0.4614 * rect.height, width: 0.065 * rect.width, height: 0.0591 * rect.height))
        return p
    }

    static func cheekL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.28 * rect.width, y: rect.minY + 0.5364 * rect.height, width: 0.08 * rect.width, height: 0.0727 * rect.height))
        return p
    }

    static func cheekR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.64 * rect.width, y: rect.minY + 0.5364 * rect.height, width: 0.08 * rect.width, height: 0.0727 * rect.height))
        return p
    }

    static func beak(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.47, 0.5545, rect))
        p.addCurve(to: pt(0.53, 0.5545, rect), control1: pt(0.48, 0.5364, rect), control2: pt(0.52, 0.5364, rect))
        p.addCurve(to: pt(0.5, 0.5909, rect), control1: pt(0.52, 0.5818, rect), control2: pt(0.505, 0.5909, rect))
        p.addCurve(to: pt(0.47, 0.5545, rect), control1: pt(0.495, 0.5909, rect), control2: pt(0.48, 0.5818, rect))
        p.closeSubpath()
        return p
    }

    private static func pt(_ x: CGFloat, _ y: CGFloat, _ rect: CGRect) -> CGPoint {
        CGPoint(x: rect.minX + x * rect.width, y: rect.minY + y * rect.height)
    }
}
