// GENERATED by ios/tools/svg2shape.py from ios/DesignAssets/feenling-hoot.svg — DO NOT EDIT.
// Edit the SVG, preview in a browser, then rerun the script.
import SwiftUI

/// Layers of the character, unit-normalized from the SVG viewBox.
/// Draw into a rect with `aspectRatio` to keep proportions.
enum HootPaths {
    static let aspectRatio: CGFloat = 0.8696

    static func tuftL(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.27, 0.1826, rect))
        p.addCurve(to: pt(0.35, 0.0174, rect), control1: pt(0.25, 0.0957, rect), control2: pt(0.29, 0.0348, rect))
        p.addCurve(to: pt(0.315, 0.2, rect), control1: pt(0.375, 0.0783, rect), control2: pt(0.355, 0.1478, rect))
        p.closeSubpath()
        return p
    }

    static func tuftR(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.73, 0.1826, rect))
        p.addCurve(to: pt(0.65, 0.0174, rect), control1: pt(0.75, 0.0957, rect), control2: pt(0.71, 0.0348, rect))
        p.addCurve(to: pt(0.685, 0.2, rect), control1: pt(0.625, 0.0783, rect), control2: pt(0.645, 0.1478, rect))
        p.closeSubpath()
        return p
    }

    static func footL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.33 * rect.width, y: rect.minY + 0.913 * rect.height, width: 0.12 * rect.width, height: 0.0609 * rect.height))
        return p
    }

    static func footR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.55 * rect.width, y: rect.minY + 0.913 * rect.height, width: 0.12 * rect.width, height: 0.0609 * rect.height))
        return p
    }

    static func body(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.5, 0.0783, rect))
        p.addCurve(to: pt(0.84, 0.5565, rect), control1: pt(0.71, 0.0783, rect), control2: pt(0.84, 0.2609, rect))
        p.addCurve(to: pt(0.5, 0.9304, rect), control1: pt(0.84, 0.8087, rect), control2: pt(0.7, 0.9304, rect))
        p.addCurve(to: pt(0.16, 0.5565, rect), control1: pt(0.3, 0.9304, rect), control2: pt(0.16, 0.8087, rect))
        p.addCurve(to: pt(0.5, 0.0783, rect), control1: pt(0.16, 0.2609, rect), control2: pt(0.29, 0.0783, rect))
        p.closeSubpath()
        return p
    }

    static func wingL(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.17, 0.4522, rect))
        p.addCurve(to: pt(0.13, 0.7739, rect), control1: pt(0.1, 0.5217, rect), control2: pt(0.08, 0.6609, rect))
        p.addCurve(to: pt(0.225, 0.5565, rect), control1: pt(0.19, 0.7391, rect), control2: pt(0.23, 0.6522, rect))
        p.closeSubpath()
        return p
    }

    static func wingR(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.83, 0.4522, rect))
        p.addCurve(to: pt(0.87, 0.7739, rect), control1: pt(0.9, 0.5217, rect), control2: pt(0.92, 0.6609, rect))
        p.addCurve(to: pt(0.775, 0.5565, rect), control1: pt(0.81, 0.7391, rect), control2: pt(0.77, 0.6522, rect))
        p.closeSubpath()
        return p
    }

    static func belly(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.27 * rect.width, y: rect.minY + 0.5391 * rect.height, width: 0.46 * rect.width, height: 0.3304 * rect.height))
        return p
    }

    static func chevron1(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.4, 0.6348, rect))
        p.addCurve(to: pt(0.52, 0.6348, rect), control1: pt(0.435, 0.6739, rect), control2: pt(0.485, 0.6739, rect))
        p.addCurve(to: pt(0.4, 0.6348, rect), control1: pt(0.485, 0.6565, rect), control2: pt(0.435, 0.6565, rect))
        p.closeSubpath()
        return p
    }

    static func chevron2(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.48, 0.713, rect))
        p.addCurve(to: pt(0.6, 0.713, rect), control1: pt(0.515, 0.7522, rect), control2: pt(0.565, 0.7522, rect))
        p.addCurve(to: pt(0.48, 0.713, rect), control1: pt(0.565, 0.7348, rect), control2: pt(0.515, 0.7348, rect))
        p.closeSubpath()
        return p
    }

    static func chevron3(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.4, 0.7913, rect))
        p.addCurve(to: pt(0.52, 0.7913, rect), control1: pt(0.435, 0.8304, rect), control2: pt(0.485, 0.8304, rect))
        p.addCurve(to: pt(0.4, 0.7913, rect), control1: pt(0.485, 0.813, rect), control2: pt(0.435, 0.813, rect))
        p.closeSubpath()
        return p
    }

    static func diskL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.24 * rect.width, y: rect.minY + 0.2522 * rect.height, width: 0.26 * rect.width, height: 0.2261 * rect.height))
        return p
    }

    static func diskR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.5 * rect.width, y: rect.minY + 0.2522 * rect.height, width: 0.26 * rect.width, height: 0.2261 * rect.height))
        return p
    }

    static func irisL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.305 * rect.width, y: rect.minY + 0.3087 * rect.height, width: 0.13 * rect.width, height: 0.113 * rect.height))
        return p
    }

    static func irisR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.565 * rect.width, y: rect.minY + 0.3087 * rect.height, width: 0.13 * rect.width, height: 0.113 * rect.height))
        return p
    }

    static func pupilL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.35 * rect.width, y: rect.minY + 0.3478 * rect.height, width: 0.06 * rect.width, height: 0.0522 * rect.height))
        return p
    }

    static func pupilR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.59 * rect.width, y: rect.minY + 0.3478 * rect.height, width: 0.06 * rect.width, height: 0.0522 * rect.height))
        return p
    }

    static func beak(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.46, 0.4348, rect))
        p.addCurve(to: pt(0.54, 0.4348, rect), control1: pt(0.48, 0.4087, rect), control2: pt(0.52, 0.4087, rect))
        p.addCurve(to: pt(0.5, 0.5, rect), control1: pt(0.52, 0.4826, rect), control2: pt(0.505, 0.5, rect))
        p.addCurve(to: pt(0.46, 0.4348, rect), control1: pt(0.495, 0.5, rect), control2: pt(0.48, 0.4826, rect))
        p.closeSubpath()
        return p
    }

    /// Paint-order layers with the authored fills.
    static let layers: [CharacterLayer] = [
        CharacterLayer(path: tuftL, color: Color(red: 0.3333, green: 0.251, blue: 0.5412)),
        CharacterLayer(path: tuftR, color: Color(red: 0.3333, green: 0.251, blue: 0.5412)),
        CharacterLayer(path: footL, color: Color(red: 0.9804, green: 0.549, blue: 0.251)),
        CharacterLayer(path: footR, color: Color(red: 0.9804, green: 0.549, blue: 0.251)),
        CharacterLayer(path: body, color: Color(red: 0.4196, green: 0.3255, blue: 0.6196)),
        CharacterLayer(path: wingL, color: Color(red: 0.3333, green: 0.251, blue: 0.5412)),
        CharacterLayer(path: wingR, color: Color(red: 0.3333, green: 0.251, blue: 0.5412)),
        CharacterLayer(path: belly, color: Color(red: 1, green: 0.9529, blue: 0.8784)),
        CharacterLayer(path: chevron1, color: Color(red: 0.4196, green: 0.3255, blue: 0.6196), opacity: 0.45),
        CharacterLayer(path: chevron2, color: Color(red: 0.4196, green: 0.3255, blue: 0.6196), opacity: 0.45),
        CharacterLayer(path: chevron3, color: Color(red: 0.4196, green: 0.3255, blue: 0.6196), opacity: 0.45),
        CharacterLayer(path: diskL, color: Color(red: 1, green: 0.9529, blue: 0.8784)),
        CharacterLayer(path: diskR, color: Color(red: 1, green: 0.9529, blue: 0.8784)),
        CharacterLayer(path: irisL, color: Color(red: 1, green: 0.7608, blue: 0.1804)),
        CharacterLayer(path: irisR, color: Color(red: 1, green: 0.7608, blue: 0.1804)),
        CharacterLayer(path: pupilL, color: Color(red: 0.1725, green: 0.1373, blue: 0.2667)),
        CharacterLayer(path: pupilR, color: Color(red: 0.1725, green: 0.1373, blue: 0.2667)),
        CharacterLayer(path: beak, color: Color(red: 0.9608, green: 0.6392, blue: 0)),
    ]

    private static func pt(_ x: CGFloat, _ y: CGFloat, _ rect: CGRect) -> CGPoint {
        CGPoint(x: rect.minX + x * rect.width, y: rect.minY + y * rect.height)
    }
}
