// GENERATED by ios/tools/svg2shape.py from ios/DesignAssets/feenling-peep.svg — DO NOT EDIT.
// Edit the SVG, preview in a browser, then rerun the script.
import SwiftUI

/// Layers of the character, unit-normalized from the SVG viewBox.
/// Draw into a rect with `aspectRatio` to keep proportions.
enum PeepPaths {
    static let aspectRatio: CGFloat = 0.9302

    static func footL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.34 * rect.width, y: rect.minY + 0.8837 * rect.height, width: 0.12 * rect.width, height: 0.0651 * rect.height))
        return p
    }

    static func footR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.54 * rect.width, y: rect.minY + 0.8837 * rect.height, width: 0.12 * rect.width, height: 0.0651 * rect.height))
        return p
    }

    static func body(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.5, 0.2326, rect))
        p.addCurve(to: pt(0.825, 0.6047, rect), control1: pt(0.7, 0.2326, rect), control2: pt(0.825, 0.3953, rect))
        p.addCurve(to: pt(0.5, 0.893, rect), control1: pt(0.825, 0.7814, rect), control2: pt(0.69, 0.893, rect))
        p.addCurve(to: pt(0.175, 0.6047, rect), control1: pt(0.31, 0.893, rect), control2: pt(0.175, 0.7814, rect))
        p.addCurve(to: pt(0.5, 0.2326, rect), control1: pt(0.175, 0.3953, rect), control2: pt(0.3, 0.2326, rect))
        p.closeSubpath()
        return p
    }

    static func wingL(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.18, 0.5395, rect))
        p.addCurve(to: pt(0.095, 0.6698, rect), control1: pt(0.12, 0.5581, rect), control2: pt(0.085, 0.6093, rect))
        p.addCurve(to: pt(0.205, 0.5767, rect), control1: pt(0.15, 0.6605, rect), control2: pt(0.19, 0.6186, rect))
        p.closeSubpath()
        return p
    }

    static func wingR(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.82, 0.5395, rect))
        p.addCurve(to: pt(0.905, 0.6698, rect), control1: pt(0.88, 0.5581, rect), control2: pt(0.915, 0.6093, rect))
        p.addCurve(to: pt(0.795, 0.5767, rect), control1: pt(0.85, 0.6605, rect), control2: pt(0.81, 0.6186, rect))
        p.closeSubpath()
        return p
    }

    static func shellCap(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.31, 0.2977, rect))
        p.addCurve(to: pt(0.5, 0.0651, rect), control1: pt(0.31, 0.1395, rect), control2: pt(0.4, 0.0651, rect))
        p.addCurve(to: pt(0.69, 0.2977, rect), control1: pt(0.6, 0.0651, rect), control2: pt(0.69, 0.1395, rect))
        p.addLine(to: pt(0.63, 0.2558, rect))
        p.addLine(to: pt(0.57, 0.307, rect))
        p.addLine(to: pt(0.5, 0.2558, rect))
        p.addLine(to: pt(0.43, 0.307, rect))
        p.addLine(to: pt(0.37, 0.2558, rect))
        p.closeSubpath()
        return p
    }

    static func eyeL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.3775 * rect.width, y: rect.minY + 0.4488 * rect.height, width: 0.065 * rect.width, height: 0.0605 * rect.height))
        return p
    }

    static func eyeR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.5575 * rect.width, y: rect.minY + 0.4488 * rect.height, width: 0.065 * rect.width, height: 0.0605 * rect.height))
        return p
    }

    static func beak(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.45, 0.5395, rect))
        p.addCurve(to: pt(0.55, 0.5395, rect), control1: pt(0.47, 0.5209, rect), control2: pt(0.53, 0.5209, rect))
        p.addCurve(to: pt(0.5, 0.5953, rect), control1: pt(0.53, 0.5767, rect), control2: pt(0.51, 0.5953, rect))
        p.addCurve(to: pt(0.45, 0.5395, rect), control1: pt(0.49, 0.5953, rect), control2: pt(0.47, 0.5767, rect))
        p.closeSubpath()
        return p
    }

    static func cheekL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.29 * rect.width, y: rect.minY + 0.5209 * rect.height, width: 0.08 * rect.width, height: 0.0744 * rect.height))
        return p
    }

    static func cheekR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.63 * rect.width, y: rect.minY + 0.5209 * rect.height, width: 0.08 * rect.width, height: 0.0744 * rect.height))
        return p
    }

    /// Paint-order layers with the authored fills.
    static let layers: [CharacterLayer] = [
        CharacterLayer(path: footL, color: Color(red: 0.9804, green: 0.549, blue: 0.251)),
        CharacterLayer(path: footR, color: Color(red: 0.9804, green: 0.549, blue: 0.251)),
        CharacterLayer(path: body, color: Color(red: 1, green: 0.7608, blue: 0.1804)),
        CharacterLayer(path: wingL, color: Color(red: 0.9608, green: 0.6392, blue: 0)),
        CharacterLayer(path: wingR, color: Color(red: 0.9608, green: 0.6392, blue: 0)),
        CharacterLayer(path: shellCap, color: Color(red: 0.9569, green: 0.9098, blue: 0.8275)),
        CharacterLayer(path: eyeL, color: Color(red: 0.1725, green: 0.1373, blue: 0.2667)),
        CharacterLayer(path: eyeR, color: Color(red: 0.1725, green: 0.1373, blue: 0.2667)),
        CharacterLayer(path: beak, color: Color(red: 0.9804, green: 0.549, blue: 0.251)),
        CharacterLayer(path: cheekL, color: Color(red: 0.9804, green: 0.549, blue: 0.251), opacity: 0.35),
        CharacterLayer(path: cheekR, color: Color(red: 0.9804, green: 0.549, blue: 0.251), opacity: 0.35),
    ]

    private static func pt(_ x: CGFloat, _ y: CGFloat, _ rect: CGRect) -> CGPoint {
        CGPoint(x: rect.minX + x * rect.width, y: rect.minY + y * rect.height)
    }
}
