// GENERATED by ios/tools/svg2shape.py from ios/DesignAssets/feenling-shelly.svg — DO NOT EDIT.
// Edit the SVG, preview in a browser, then rerun the script.
import SwiftUI

/// Layers of the character, unit-normalized from the SVG viewBox.
/// Draw into a rect with `aspectRatio` to keep proportions.
enum ShellyPaths {
    static let aspectRatio: CGFloat = 1.2941

    static func head(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.0273 * rect.width, y: rect.minY + 0.5294 * rect.height, width: 0.2 * rect.width, height: 0.2588 * rect.height))
        return p
    }

    static func eye(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.0727 * rect.width, y: rect.minY + 0.5647 * rect.height, width: 0.0727 * rect.width, height: 0.1059 * rect.height))
        return p
    }

    static func pupil(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.1 * rect.width, y: rect.minY + 0.6059 * rect.height, width: 0.0364 * rect.width, height: 0.0471 * rect.height))
        return p
    }

    static func smile(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.0682, 0.7176, rect))
        p.addCurve(to: pt(0.1409, 0.7176, rect), control1: pt(0.0818, 0.7471, rect), control2: pt(0.1273, 0.7471, rect))
        p.addCurve(to: pt(0.0682, 0.7176, rect), control1: pt(0.1273, 0.7706, rect), control2: pt(0.0818, 0.7706, rect))
        p.closeSubpath()
        return p
    }

    static func tail(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.8636, 0.6588, rect))
        p.addCurve(to: pt(0.9091, 0.7118, rect), control1: pt(0.9045, 0.6353, rect), control2: pt(0.9318, 0.6647, rect))
        p.addCurve(to: pt(0.8636, 0.6588, rect), control1: pt(0.8909, 0.7, rect), control2: pt(0.8727, 0.6824, rect))
        p.closeSubpath()
        return p
    }

    static func legL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.3091 * rect.width, y: rect.minY + 0.8059 * rect.height, width: 0.1273 * rect.width, height: 0.1059 * rect.height))
        return p
    }

    static func legR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.6273 * rect.width, y: rect.minY + 0.8059 * rect.height, width: 0.1273 * rect.width, height: 0.1059 * rect.height))
        return p
    }

    static func shell(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.1455, 0.6235, rect))
        p.addCurve(to: pt(0.5136, 0.2353, rect), control1: pt(0.1455, 0.3647, rect), control2: pt(0.3182, 0.2353, rect))
        p.addCurve(to: pt(0.8818, 0.6235, rect), control1: pt(0.7091, 0.2353, rect), control2: pt(0.8818, 0.3647, rect))
        p.addCurve(to: pt(0.5136, 0.7824, rect), control1: pt(0.8818, 0.7294, rect), control2: pt(0.8091, 0.7824, rect))
        p.addCurve(to: pt(0.1455, 0.6235, rect), control1: pt(0.2182, 0.7824, rect), control2: pt(0.1455, 0.7294, rect))
        p.closeSubpath()
        return p
    }

    static func plateL(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.2636 * rect.width, y: rect.minY + 0.4353 * rect.height, width: 0.1273 * rect.width, height: 0.1647 * rect.height))
        return p
    }

    static func plateC(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.4409 * rect.width, y: rect.minY + 0.3294 * rect.height, width: 0.1455 * rect.width, height: 0.1882 * rect.height))
        return p
    }

    static func plateR(in rect: CGRect) -> Path {
        var p = Path()
        p.addEllipse(in: CGRect(x: rect.minX + 0.6364 * rect.width, y: rect.minY + 0.4353 * rect.height, width: 0.1273 * rect.width, height: 0.1647 * rect.height))
        return p
    }

    static func rim(in rect: CGRect) -> Path {
        var p = Path()
        p.move(to: pt(0.1955, 0.7412, rect))
        p.addLine(to: pt(0.8318, 0.7412, rect))
        p.addCurve(to: pt(0.8636, 0.7824, rect), control1: pt(0.85, 0.7412, rect), control2: pt(0.8636, 0.7588, rect))
        p.addCurve(to: pt(0.8318, 0.8235, rect), control1: pt(0.8636, 0.8059, rect), control2: pt(0.85, 0.8235, rect))
        p.addLine(to: pt(0.1955, 0.8235, rect))
        p.addCurve(to: pt(0.1636, 0.7824, rect), control1: pt(0.1773, 0.8235, rect), control2: pt(0.1636, 0.8059, rect))
        p.addCurve(to: pt(0.1955, 0.7412, rect), control1: pt(0.1636, 0.7588, rect), control2: pt(0.1773, 0.7412, rect))
        p.closeSubpath()
        return p
    }

    /// Paint-order layers with the authored fills.
    static let layers: [CharacterLayer] = [
        CharacterLayer(path: head, color: Color(red: 0.4235, green: 0.7529, blue: 0.5333)),
        CharacterLayer(path: eye, color: Color(red: 1, green: 1, blue: 1)),
        CharacterLayer(path: pupil, color: Color(red: 0.1725, green: 0.1373, blue: 0.2667)),
        CharacterLayer(path: smile, color: Color(red: 0.2314, green: 0.4902, blue: 0.3294)),
        CharacterLayer(path: tail, color: Color(red: 0.4235, green: 0.7529, blue: 0.5333)),
        CharacterLayer(path: legL, color: Color(red: 0.4235, green: 0.7529, blue: 0.5333)),
        CharacterLayer(path: legR, color: Color(red: 0.4235, green: 0.7529, blue: 0.5333)),
        CharacterLayer(path: shell, color: Color(red: 0.2471, green: 0.6078, blue: 0.3725)),
        CharacterLayer(path: plateL, color: Color(red: 0.1804, green: 0.4784, blue: 0.2863)),
        CharacterLayer(path: plateC, color: Color(red: 0.1804, green: 0.4784, blue: 0.2863)),
        CharacterLayer(path: plateR, color: Color(red: 0.1804, green: 0.4784, blue: 0.2863)),
        CharacterLayer(path: rim, color: Color(red: 0.5569, green: 0.8157, blue: 0.6471)),
    ]

    private static func pt(_ x: CGFloat, _ y: CGFloat, _ rect: CGRect) -> CGPoint {
        CGPoint(x: rect.minX + x * rect.width, y: rect.minY + y * rect.height)
    }
}
